### PR TITLE
First brief conversion to scss.

### PR DESCRIPTION
**Pull request by liitlelenim**
It's working but I want to make it even better in the future. This commit is a solid foundation that can already be used as project core.

### CODE REVIEW

**Comment by kimlimjustin** [comment]
This pull request will be merged soon after version 0.1.1 released and will be included in v.0.2.

**Comment by liitlelenim** [comment]
I am wondering when version 0.1.1 will be released, thanks in advance for an answer.

**Comment by kimlimjustin** [comment]
We'll release it maybe tomorrow(I use `maybe` because of timezone). For more information, I've created Fire UI release team. I'll invite you:)

**Comment by liitlelenim** [comment]
Our timezones are pretty distant because I am living in Poland 😄, although I am looking forward to our further collaboration and of course your invitation 😀.  I got really attached to this project and I can't wait to develop it further.

**Comment by kimlimjustin** [comment]
Thank you so much bro...

**Comment by liitlelenim** [comment]
I should be thankful for letting me be a part of this project 😅

**Pull request merged**
